const constants = {
  GET_PHOTOS_REQUEST: 'GET_REQUEST',
  GET_PHOTOS_SUCCESS: 'GET_PHOTOS_SUCCESS',
  GET_PHOTOS_ERROR: 'GET_PHOTOS_ERROR',
  GET_MANIFEST: 'GET_MANIFEST',
};

export default constants;
